import {
  RiAddCircleLine,
  RiArrowLeftSLine,
  RiAddLine,
  RiBook2Fill,
  RiCalendarLine,
  RiCameraLine,
  RiChat3Line,
  RiEdit2Line,
  RiHeartLine,
  RiImageLine,
  RiLogoutBoxRLine,
  RiMailLine,
  RiMore2Fill,
  RiMoreLine,
  RiNotification2Line,
  RiRepeat2Fill,
  RiSearchLine,
  RiSettings2Line,
  RiSubtractLine,
  RiTeamLine,
  RiUser3Line,
  RiVidiconLine,
  RiHeartFill,
  RiLink,
  RiArrowRightCircleFill,
  RiArrowLeftCircleFill,
  RiGiftLine,
  RiUserAddLine,
  RiHome6Line,
  RiWalletLine,
  RiShoppingCartLine,
  RiArrowDownSFill,
  RiCloseLine,
  RiShoppingBasketLine,
} from 'react-icons/ri';

export const Icons = {
  User: RiUser3Line,
  Search: RiSearchLine,
  Book: RiBook2Fill,
  Add: RiAddLine,
  AddCircle: RiAddCircleLine,
  Mail: RiMailLine,
  Setting: RiSettings2Line,
  Minus: RiSubtractLine,
  Chat: RiChat3Line,
  Edit: RiEdit2Line,
  HeartLine: RiHeartLine,
  HeartFill: RiHeartFill,
  Camera: RiCameraLine,
  Photos: RiImageLine,
  Notification: RiNotification2Line,
  Video: RiVidiconLine,
  ArrowLeft: RiArrowLeftSLine,
  Logout: RiLogoutBoxRLine,
  VerticalMenu: RiMore2Fill,
  HorizontalMenu: RiMoreLine,
  Groups: RiTeamLine,
  Album: RiRepeat2Fill,
  TimeLine: RiCalendarLine,
  Link: RiLink,
  ArrowRightFill: RiArrowRightCircleFill,
  ArrowLeftFill: RiArrowLeftCircleFill,
  Gift: RiGiftLine,
  AddUser: RiUserAddLine,
  ArrowDropDown: RiArrowDownSFill,
  Home: RiHome6Line,
  Wallet: RiWalletLine,
  Cart: RiShoppingCartLine,
  Close: RiCloseLine,
  Market: RiShoppingBasketLine,
};
